apiVersion: v1
kind: Service

metadata:
  name: flask-service
  labels:
    name: flask-service
    app: example-flask-app

spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30008
  selector:
    name: flask-app-pod
    app: example-flask-app
