apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-app-deploy
  labels:
    name: flask-app-deploy
    app: exmaple-flask-app

spec:
  replicas: 1

  selector:
    matchLabels:
      name: flask-app-pod
      app: example-flask-app

  template:
    metadata:
      name: flask-app-pod
      labels:
        name: flask-app-pod
        app: example-flask-app
    spec:
      containers:
      - name: flask-container
        image: sreekanthraju999/myflask-app:latest
        ports:
          - containerPort: 5000
